export const GET_FORECAST = 'GET_FORECAST';

export const RESET_COORD_ERROR = 'RESET_COORD_ERROR';
export const FETCH_COORD_REQUEST = 'FETCH_COORD_REQUEST';
export const FETCH_COORD_ERROR = 'FETCH_COORD_ERROR';
export const CHANGE_COORD_MAP = 'CHANGE_COORD_MAP';
export const SET_COORD_POPUP = 'SET_COORD_POPUP';

export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const SHOW_POPUP = 'SHOW_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const MAPBOX_TOKEN =
    'pk.eyJ1IjoiYXJ0eW9tbG95a28iLCJhIjoiY2ptdXF1Y3M0MDI1dDN3bDV6YzVuMDA1eSJ9.wl1_CVDeH44zMDWjSDZTCw';
export const OPEN_WEATHER_TOKEN = 'efe47e164e1c22e9d4ecfd8f4ea0564a';
